version: "3.9"

services:
  db:
    image: postgres:17.4
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/education
    command: ["./wait-for-it.sh", "db:5432", "--",
              "python", "/education/manage.py", "runserver",
              "0.0.0.0:8000"]
    environment:
      - DJANGO_SETTINGS_MODULE=education.settings.prod
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
