services:

  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    build: .
    entrypoint: ["/code/entrypoint.sh"]
    restart: always
    volumes:
      - .:/code
      - socket:/socket
    environment:
      - DJANGO_SETTINGS_MODULE=education.settings.prod
      # - DJANGO_SETTINGS_MODULE=education.settings.local
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
      - socket:/socket
    ports:
      - "80:80"
      - "443:443"

volumes:
  socket:
